language: c

os:
  - linux

sudo: false

notifications:
  email: false

env:
  global:
    - CONDA_DEPENDENCIES="pytest pytest-cov nomkl"
    - PIP_DEPENDENCIES="sphinx-automodapi numpydoc sphinx_rtd_theme pytest-faulthandler codecov"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - python setup.py sdist
  - cd dist; pip install *.tar.gz --verbose; cd ..
  - pytest wwt_api_client --cov wwt_api_client
  - cd docs ; make html linkcheck ; cd ..

after_success:
  - codecov
